### ISSUE TITLE
Error: any ideas?

### ISSUE THREAD

**Issue by PTGHJJD** [offish/opplast#11]
Hey Thanks for doing this.  Very cool and easy.  

it was working fine until today.  i did pull your latest release.  getting this error today using your sample code with a valid file location. on Windows 10 and FF 86.0 (64-bit)

PS C:\Users\johnj> & python c:/Users/johnj/Desktop/auto-downloader/TestUpload03152021.py
DEBUG: Firefox is now running
DEBUG: Trying to upload "D:/ToYouTube/upload/365tour.mp4" to YouTube...
DEBUG: Trying to set "My YouTube Title" as title...
DEBUG: Trying to set "My YouTube Description" as description...
Traceback (most recent call last):
  File "c:/Users/johnj/Desktop/auto-downloader/TestUpload03152021.py", line 8, in <module>
    was_uploaded, video_id = upload.upload(
  File "C:\Users\johnj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\opplast\upload.py", line 78, in upload        
    container = self.driver.find_element_by_xpath(DESCRIPTION_CONTAINER)
  File "C:\Users\johnj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 
394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\johnj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 
976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\johnj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 
321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\johnj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: /html/body/ytcp-uploads-dialog/tp-yt-paper-dialog/div/ytcp-animatable[1]/ytcp-uploads-details/div/ytcp-uploads-basics/ytcp-mention-textbox[2]

**Comment by offish** [comment]
Seems like YouTube have changed around yet again. I'll update it now.

**Comment by offish** [comment]
Should be fixed now. Try running `pip install --upgrade opplast` and upload again.

**Comment by PTGHJJD** [comment]
thanks for the quick response.  :>  so getting this error now. I appreciate your help.

![image](https://user-images.githubusercontent.com/80021576/111218874-f4008800-859c-11eb-851b-a74a144442e9.png)

**Comment by offish** [comment]
Hmm, that's weird. Just tried it again and it works for me. It was uploading when you opened the issue, but now it isn't? I didn't update anything surrounding the actual uploading so that's quite weird. Try to set `headless=False` and see what happens. I don't really have any other advice on how to fix this.

**Comment by PTGHJJD** [comment]
I will try again. And reset things.

I will probably make a new FF/YT profile as well
Yes it worked fine yesterday.
Thank you


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by PTGHJJD** [comment]
Thanks.  It does seem weird.  I created a new YT profile and tested with both the old a new profile.

And got different errors hmmm odd.

It only works headless from what I tell

Here is the output from both attempts. I wonder if its different in the US?

I will run some debug on it.

thanks for your help.

First attempt

PS C:\Users\johnj\Desktop\auto-downloader\config> & C:/Users/johnj/AppData/Local/Microsoft/WindowsApps/PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0/python.exe c:/Users/johnj/Desktop/auto-downloader/PYYTUploader-V3d.py
DEBUG: Firefox is now running
DEBUG: Trying to upload "D:/ToYouTube/upload/365tour.mp4" to YouTube...
DEBUG: Trying to set "365 Propery Tour" as title...
DEBUG: Trying to set video to "Not made for kids"...
Traceback (most recent call last):
  File "c:/Users/johnj/Desktop/auto-downloader/PYYTUploader-V3d.py", line 37, in <module>
    was_uploaded, video_id = upload.upload(
  File "C:\Users\johnj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\opplast\upload.py", line 135, in upload
    self.driver.find_element_by_id(NEXT_BUTTON).click()
  File "C:\Users\johnj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\johnj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\johnj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\johnj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: Element <ytcp-button id="next-button" class="style-scope ytcp-uploads-dialog"> could not be scrolled into view


second attempt

PS C:\Users\johnj\Desktop\auto-downloader\config> & C:/Users/johnj/AppData/Local/Microsoft/WindowsApps/PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0/python.exe c:/Users/johnj/Desktop/auto-downloader/TestUpload03152021.py
DEBUG: Firefox is now running
DEBUG: Trying to upload "D:/ToYouTube/upload/365tour.mp4" to YouTube...
Traceback (most recent call last):
  File "c:/Users/johnj/Desktop/auto-downloader/TestUpload03152021.py", line 9, in <module>
    was_uploaded, video_id = upload.upload(
  File "C:\Users\johnj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\opplast\upload.py", line 55, in upload
    self.driver.find_element_by_xpath(INPUT_FILE_VIDEO).send_keys(path)
  File "C:\Users\johnj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\johnj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\johnj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\johnj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: ***@***.***='file']

PS C:\Users\johnj\Desktop\auto-downloader\config>

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
